### ISSUE TITLE
Feature: Select queries

### ISSUE THREAD

**Issue by var-che** [igalklebanov/kysely-surrealdb#15]
### Is this feature request related to a problem?
Yes, there is no way to query the database using this library, and the `select` and `selectFrom` functions will solve the problem.

### Describe the solution
The solution would be to "port" the existing functions from the main kysely. 

### Alternative methods
Another method would be to implement a raw SQL function allowing the user to insert raw SurrealQL and query it that way.

### SurrealDB version
1.3.0+20240222.73a90ac

### Is there an existing issue for this?

- [x] I have searched the existing issues

**Comment by igalklebanov** [comment]
Hey 👋 

> Yes, there is no way to query the database using this library

How so?

>  and the select and selectFrom functions will solve the problem.
>
> Describe the solution
> The solution would be to "port" the existing functions from the main kysely.

Do you claim they don't exist in this library?

Are you familiar with the concept of class inheritance in OOP?

`SurrealKysely` extends `Kysely`.

> Alternative methods
> 
> Another method would be to implement a raw SQL function allowing the user to insert raw SurrealQL and query it that way.

Such functionality already exists in kysely, thus exists in this library.
