### ISSUE TITLE
Latest SurrealQL Features

### ISSUE THREAD

**Issue by DrewRidley** [igalklebanov/kysely-surrealdb#6]
Hey,

Great work with this project! is it still under active development? If so, is there an eta for when stuff like ``if`` statements, nested clauses and websockets will be supported?

**Comment by igalklebanov** [comment]
Hey 👋


I'll examine these and other gaps and plan the next steps. What's currently blocking you the most?

**Comment by DrewRidley** [comment]
Currently my biggest concern would be the lack of complex relational queries.

``SELECT ->knows->(? AS f1)->knows->(? AS f2)->(knows, likes AS e3 WHERE influencer = true)->(? AS f3) FROM person:tobie;
``
 I am unaware of a way to execute a query like this with this library (this is definitely a more extreme example though)

Websockets I think I could probably manage to implement myself and submit a PR. I really don't know a lot about query builders so I don't know how much I could help in building a relational query builder.

**Comment by igalklebanov** [comment]
The initial goal was to cover everything in the official docs, and allow more advanced undocumented stuff through raw sql & escape hatches.

There's a PR tackling surreal-specific `select` query stuff, and a branch tackling `if` queries.

I'd see if I can finish those soon.

A PR with a dialect for the websocket client would be much appreciated..

**Comment by igalklebanov** [comment]
Just released version 0.6.0 with `IF ELSE` statement support.

**Comment by igalklebanov** [comment]
Just released version 0.7.0 with `SurrealDbWebSocketsDialect`.
